#pragma once

#include <map>
#include <memory>
#include <string>
#include <optional>

#include <nlohmann/json.hpp>

#include <metatomic.h>
#include <metatomic/errors.hpp>
#include <metatomic/model.hpp>

namespace metatomic {
    /// Load the shared library at `path` and register the plugin contained
    /// within. The library must export the symbols generated by the
    /// `MTA_REGISTER_PLUGIN` macro.
    ///
    /// @param path path to the plugin shared library
    inline void load_plugin(const std::string& path) {
        details::check_status(mta_load_plugin(path.c_str()));
    }

    /// Load a model from `load_from` with the given options.
    ///
    /// If `plugin_name` is `std::nullopt`, metatomic will try to determine the
    /// correct plugin to use by checking the `load_from` parameter. If we can
    /// not determine the correct plugin, we then try to load the model with
    /// each registered plugin until one succeeds.
    ///
    /// If `plugin_name` is given, then we only try to load the model with the
    /// specified plugin, and return an error if the plugin can not load the
    /// model.
    ///
    /// @param load_from where to load the model from (e.g. a file path, a
    ///     model name, etc.)
    /// @param plugin_name optional name of the plugin to use for loading the
    ///     model, or `std::nullopt` to let metatomic search
    /// @param options_json optional JSON object containing string keys and
    ///     string values for loading the model
    /// @return the loaded model
    inline ExternalModel load_model(
        const std::string& load_from,
        std::optional<std::string> options_json = std::nullopt,
        std::optional<std::string> plugin_name = std::nullopt
    ) {
        mta_model_t model;
        const char* plugin_name_ptr = nullptr;
        if (plugin_name.has_value()) {
            plugin_name_ptr = plugin_name->c_str();
        }

        const char* options_json_ptr = nullptr;
        if (options_json.has_value()) {
            options_json_ptr = options_json->c_str();
        }

        details::check_status(mta_load_model(
            load_from.c_str(),
            options_json_ptr,
            plugin_name_ptr,
            &model
        ));

        return ExternalModel(model);
    }

    namespace details {
        using load_model_t = std::unique_ptr<BaseModel> (*)(
            const std::string& load_from,
            const std::map<std::string, std::string>& options
        );

        /// `load_model` callback for a `mta_plugin_t` built by `MTA_REGISTER_CXX_PLUGIN`
        inline mta_status_t cxx_plugin_load_model(
            const char* load_from,
            const char* options_json,
            mta_model_t* model,
            load_model_t load_model_fn
        ) {
            std::unique_ptr<BaseModel> cpp_model;
            auto status = metatomic::details::catch_exceptions([&]() {
                auto options_obj = nlohmann::json::parse(options_json);
                auto options = options_obj.get<std::map<std::string, std::string>>();
                cpp_model = load_model_fn(std::string(load_from), options);
            });

            if (status != MTA_SUCCESS) {
                // exception was caught while trying to load the model
                // stop the plugin search and report the error
                return status;
            }

            if (cpp_model == nullptr) {
                // the plugin could not load this model
                return MTA_UNSUPPORTED_MODEL_ERROR;
            }

            *model = BaseModel::to_mta_model(std::move(cpp_model));
            return MTA_SUCCESS;
        }
    } // namespace details
} // namespace metatomic


#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-macros"
#endif


/// Plugin entry point for a C++ plugin.
///
/// This should be used once in a C++ plugin shared library. `plugin_name` is
/// the name of the plugin, and `load_model_fn` must be a plain function with
/// the signature:
///
/// ```cpp
/// std::unique_ptr<metatomic::BaseModel> load_model_fn(
///     const std::string& load_from,
///     const std::map<std::string, std::string>& options
/// );
/// ```
///
/// `load_model_fn` MUST return `nullptr` if it can not load the model
/// described by `load_from`, so metatomic can try another plugin.
///
/// Only one `MTA_REGISTER_CXX_PLUGIN` can be used per shared library.
#define MTA_REGISTER_CXX_PLUGIN(plugin_name, load_model_fn)                         \
    MTA_REGISTER_PLUGIN(register_fn, {                                              \
        static_assert(                                                              \
            std::is_convertible<                                                    \
                decltype(load_model_fn), metatomic::details::load_model_t           \
            >::value,                                                               \
            "MTA_REGISTER_CXX_PLUGIN: load_model_fn must be callable as "           \
            "std::unique_ptr<metatomic::BaseModel>("                                \
            "std::string, std::map<std::string, std::string>)"                      \
        );                                                                          \
                                                                                    \
        static mta_plugin_t PLUGIN {                                                \
            /*abi_version*/ MTA_ABI_VERSION,                                        \
            /*name*/ plugin_name,                                                   \
            /*load_model*/ [](                                                      \
                const char* load_from, const char* options_json, mta_model_t* model \
            ) {                                                                     \
                return metatomic::details::cxx_plugin_load_model(                   \
                    load_from, options_json, model, load_model_fn                   \
                );                                                                  \
            }                                                                       \
        };                                                                          \
        return register_fn(PLUGIN);                                                 \
    })

#ifdef __clang__
#pragma clang diagnostic pop
#endif
