#pragma once

#include <string>

#include <metatomic.h>
#include <metatomic/errors.hpp>

namespace metatomic {
    /// Load the shared library at `path` and register the plugin contained
    /// within. The library must export the symbols generated by the
    /// `MTA_REGISTER_PLUGIN` macro.
    ///
    /// @param path path to the plugin shared library
    inline void load_plugin(const std::string& path) {
        auto status = mta_load_plugin(path.c_str());
        details::check_status(status);
    }

    /// Load a model from `load_from` with the given options.
    ///
    /// If `plugin_name` is empty, metatomic will try to determine the correct
    /// plugin to use by checking the `load_from` parameter. If we can not
    /// determine the correct plugin, we then try to load the model with each
    /// registered plugin until one succeeds.
    ///
    /// If `plugin_name` is given, then we only try to load the model with the
    /// specified plugin, and return an error if the plugin can not load the
    /// model.
    ///
    /// @param load_from where to load the model from (e.g. a file path, a
    ///     model name, etc.)
    /// @param plugin_name optional name of the plugin to use for loading the
    ///     model, or empty to let metatomic search
    /// @param options_json optional JSON object containing string keys and
    ///     string values for loading the model
    /// @return the loaded model
    inline mta_model_t load_model(
        const std::string& load_from,
        const std::string& options_json = "",
        const std::string& plugin_name = ""
    ) {
        mta_model_t model;
        const char* plugin_name_ptr = plugin_name.empty() ? nullptr : plugin_name.c_str();
        const char* options_json_ptr = options_json.empty() ? nullptr : options_json.c_str();

        auto status = mta_load_model(load_from.c_str(), options_json_ptr, plugin_name_ptr, &model);
        details::check_status(status);

        return model;
    }
} // namespace metatomic
