use std::ffi::{CStr, c_char};

use super::catch_unwind;
use super::{mta_model_t, mta_status_t};
use crate::Error;
use crate::Plugin;

/// A metatomic plugin definition.
#[allow(non_camel_case_types)]
#[repr(C)]
pub struct mta_plugin_t {
    /// ABI version this plugin was compiled against, this should be set to
    /// `MTA_ABI_VERSION` when creating the plugin struct.
    pub abi_version: i32,

    /// Name of the plugin, as a null-terminated UTF-8 string. This is the name
    /// specified in `mta_load_model` when trying to load a model with a
    /// specific plugin. The name must be unique among all registered plugins.
    pub name: *const c_char,

    /// Callback function to load a model. This function should try to load a
    /// model from `load_from` (which can be a file path, a model name, etc.)
    /// and a set of key/values options passed as a JSON string.
    ///
    /// If the plugin can load the model, it should fill `model` with a pointer
    /// to a valid `mta_model_t` struct and return `MTA_SUCCESS`. If the data in
    /// `load_from` does not correspond to a model supported by the plugin, it
    /// should return `MTA_MODEL_NOT_SUPPORTED_ERROR`. If an error occurs while
    /// loading the model, it should return another status code and save an
    /// error message with `mta_set_last_error`.
    ///
    /// @param load_from a null-terminated UTF-8 string describing where to load
    ///     the model from (e.g. a file path, a model name, etc.). The interpretation
    ///     of this string is up to the plugin.
    /// @param options_json a null-terminated UTF-8 string containing a set of
    ///     string keys and string value options for loading the model.
    /// @param model output pointer to the loaded model. The caller takes ownership of
    ///     the model and must unload it when the model is no longer needed.
    /// @return `MTA_SUCCESS` if the model was loaded successfully, `MTA_MODEL_NOT_SUPPORTED_ERROR`
    ///    if the plugin can not load the model, or another status code if an error occurs.
    pub load_model: Option<unsafe extern "C" fn(
        load_from: *const c_char,
        options_json: *const c_char,
        model: *mut mta_model_t,
    ) -> mta_status_t>,
}

unsafe impl Send for mta_plugin_t {}

/// Register a plugin. This is passed as a callback to the `MTA_REGISTER_PLUGIN`
/// macro, and should not be called directly by C or C++ plugin implementations.
///
/// @param plugin the plugin to register
/// @return `MTA_SUCCESS` if the plugin was registered successfully, or another
///     status code if an error occurs. You can get more details about the error
///     with `mta_last_error`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mta_register_plugin(plugin: mta_plugin_t) -> mta_status_t {
    catch_unwind(move || {
        let plugin = Plugin::new(plugin)?;
        crate::plugin::register_plugin(plugin)?;
        Ok(())
    })
}

/// Load the shared library at `path` and register the plugin contained within.
///
/// The library must export the symbols generated by the `MTA_REGISTER_PLUGIN`
/// macro.
///
/// @param path a null-terminated UTF-8 string containing the path to the plugin
///     shared library
/// @return `MTA_SUCCESS` if the plugin was loaded successfully, or another
///     status code if an error occurs. You can get more details about the
///     error with `mta_last_error`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mta_load_plugin(path: *const c_char) -> mta_status_t {
    catch_unwind(move || {
        check_pointers_non_null!(path);

        let path = unsafe { CStr::from_ptr(path) }
            .to_str()
            .map_err(|_| {
                Error::InvalidParameter("invalid UTF-8 in plugin path".into())
            })?;

        crate::plugin::load_plugin(path)
    })
}

/// Load a model from `load_from` with the given options.
///
/// If `plugin_name` is a NULL pointer, metatomic will try to determine the
/// correct plugin to use by checking the `load_from` parameter. If we can not
/// determine the correct plugin, we then try to load the model with each
/// registered plugin until one succeeds.
///
/// If `plugin_name` is given, then we only try to load the model with the
/// specified plugin, and return an error if the plugin can not load the model.
///
/// @param plugin_name optional null-terminated UTF-8 string containing the name
///     of the plugin to use for loading the model, or `NULL` to let metatomic
///     search for a correct plugin
/// @param load_from a null-terminated UTF-8 string describing where to load the
///     model from (e.g. a file path, a model name, etc.). The interpretation
///     of this string is up to the plugin.
/// @param options_json a null-terminated UTF-8 string containing a set of string
///     keys and string value options for loading the model. The interpretation
///     of these options is up to the plugin.
/// @param model output pointer to the loaded model. The caller takes ownership of
///     the model and must unload it when the model is no longer needed.
/// @return `MTA_SUCCESS` if the model was loaded successfully, or another
///     status code if an error occurs. You can get more details about the
///     error with `mta_last_error`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mta_load_model(
    load_from: *const c_char,
    options_json: *const c_char,
    plugin_name: *const c_char,
    model: *mut mta_model_t,
) -> mta_status_t {
    let unwind_wrapper = std::panic::AssertUnwindSafe(model);

    catch_unwind(move || {
        check_pointers_non_null!(load_from, model);

        let plugin_name = if plugin_name.is_null() {
            None
        } else {
            let cstr = unsafe { CStr::from_ptr(plugin_name) };
            Some(cstr.to_str().map_err(|_| {
                Error::InvalidParameter("invalid UTF-8 in plugin name".into())
            })?)
        };

        let options_json =  if options_json.is_null() {
            c"{}"
        } else {
            unsafe { CStr::from_ptr(options_json) }
        };

        let options_str = options_json.to_str().map_err(|_| {
            Error::InvalidParameter("invalid UTF-8 in options JSON".into())
        })?;

        let options = json::parse(options_str).map_err(
            |e| Error::Serialization(format!("JSON parsing error: {}", e))
        )?;
        if !options.is_object() {
            return Err(Error::Serialization("JSON options must be an object in `mta_load_model`".into()))
        }

        // just some validation, we pass the raw JSON down to the plugins
        for (key, value) in options.entries() {
            if !value.is_string() {
                return Err(Error::InvalidParameter(format!(
                    "JSON option '{}' has a non-string value in `mta_load_model`",
                    key
                )));
            }
        }

        let load_from = unsafe { CStr::from_ptr(load_from) };
        let loaded = crate::plugin::load_model(load_from, options_json, plugin_name)?;

        let _ = &unwind_wrapper;
        unsafe {
            *unwind_wrapper.0 = loaded.into_raw();
        }
        Ok(())
    })
}
