use std::ffi::c_char;

use super::{mta_model_t, mta_status_t};
use crate::plugin::MTA_ABI_VERSION;

/// A metatomic plugin definition.
#[allow(non_camel_case_types)]
#[repr(C)]
pub struct mta_plugin_t {
    /// ABI version this plugin was compiled against.
    pub abi_version: i32,

    /// Null-terminated UTF-8 plugin name.
    pub name: *const c_char,

    /// Load a model from a path and a JSON object containing loading options.
    pub load_model: Option<
        unsafe extern "C" fn(
            load_from: *const c_char,
            options_json: *const c_char,
            model: *mut mta_model_t,
        ) -> mta_status_t,
    >,
}

unsafe impl Send for mta_plugin_t {}
unsafe impl Sync for mta_plugin_t {}

/// Register a plugin in the current process.
///
/// This checks the plugin ABI version before adding the plugin to the global
/// registry. In plugin shared libraries, prefer the `MTA_PLUGIN` macro.
#[no_mangle]
pub extern "C" fn mta_register_plugin(plugin: mta_plugin_t) -> mta_status_t {
    super::catch_unwind(move || {
        if plugin.abi_version != MTA_ABI_VERSION {
            return Err(crate::Error::InvalidParameter(format!(
                "can not register plugin '{}': plugin ABI version is {}, but this metatomic library expects {}",
                unsafe { plugin_name_for_error(plugin.name) },
                plugin.abi_version,
                MTA_ABI_VERSION,
            )));
        }

        crate::plugin::register_plugin(crate::plugin::Plugin::new(plugin))
    })
}

/// Load and register a plugin from a shared library.
///
/// The library must export the symbols generated by the `MTA_PLUGIN` macro.
#[no_mangle]
pub unsafe extern "C" fn mta_load_plugin(path: *const c_char) -> mta_status_t {
    super::catch_unwind(move || {
        check_pointers_non_null!(path);

        let path = std::ffi::CStr::from_ptr(path)
            .to_str()
            .map_err(|_| crate::Error::InvalidParameter("invalid UTF-8 in plugin path".into()))?;

        crate::plugin::load_plugin(path)
    })
}

/// Load a model using a registered plugin.
///
/// If `plugin_name` is null, all registered plugins are tried until one can
/// load the model. If `options_json` is null, an empty JSON object is used.
#[no_mangle]
pub unsafe extern "C" fn mta_load_model(
    plugin_name: *const c_char,
    load_from: *const c_char,
    options_json: *const c_char,
    model: *mut mta_model_t,
) -> mta_status_t {
    let unwind_wrapper = std::panic::AssertUnwindSafe(model);

    super::catch_unwind(move || {
        check_pointers_non_null!(load_from, model);

        let plugin_name = if plugin_name.is_null() {
            None
        } else {
            Some(std::ffi::CStr::from_ptr(plugin_name).to_str().map_err(|_| {
                crate::Error::InvalidParameter("invalid UTF-8 in plugin name".into())
            })?)
        };

        let load_from = std::ffi::CStr::from_ptr(load_from)
            .to_str()
            .map_err(|_| crate::Error::InvalidParameter("invalid UTF-8 in model path".into()))?;

        let options_json = if options_json.is_null() {
            "{}"
        } else {
            std::ffi::CStr::from_ptr(options_json).to_str().map_err(|_| {
                crate::Error::InvalidParameter("invalid UTF-8 in model loading options".into())
            })?
        };

        let loaded = crate::plugin::load_model_json(plugin_name, load_from, options_json)?;

        unsafe {
            *unwind_wrapper.0 = loaded.into_raw();
        }
        return Ok(());
    })
}

unsafe fn plugin_name_for_error(name: *const c_char) -> String {
    if name.is_null() {
        return "<unknown>".into();
    }

    return std::ffi::CStr::from_ptr(name).to_string_lossy().into_owned();
}
