version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily # Temporarily set to daily to test
    open-pull-requests-limit: 1
    groups:
      action-dependencies:
        patterns:
          - "*" # A wildcard to create one PR for all dependencies in the ecosystem
