#ifndef METATOMIC_H
#define METATOMIC_H

/* ============    Automatically generated file, DO NOT EDIT.     ============== *
 *                                                                               *
 *    This file is automatically generated from the metatomic sources,           *
 *    using cbindgen. If you want to change this file (including documentation), *
 *    make the corresponding changes in the rust sources and regenerate it.      *
 * ============================================================================= */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "metatomic/version.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Get the runtime version of the metatomic library as a string.
 *
 * This version follows the `<major>.<minor>.<patch>[-<dev>]` format.
 */
const char *mta_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* METATOMIC_H */
