#ifndef METATOMIC_H
#define METATOMIC_H

/* ============    Automatically generated file, DO NOT EDIT.     ============== *
 *                                                                               *
 *    This file is automatically generated from the metatomic sources,           *
 *    using cbindgen. If you want to change this file (including documentation), *
 *    make the corresponding changes in the rust sources and regenerate it.      *
 * ============================================================================= */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "metatensor.h"
#include "metatomic/version.h"


/** Heap allocated storage for mta_string_t */
typedef struct mta_opaque_string_t mta_opaque_string_t;

/**
 * TODO
 */
#define MTA_ABI_VERSION 1

/**
 * Status type returned by all functions in the C API.
 *
 * The value 0 (`MTA_SUCCESS`) indicates success, while any non-zero value indicates an error.
 */
typedef enum mta_status_t {
  /**
   * Status code indicating success
   */
  MTA_SUCCESS = 0,
  /**
   * Status code indicating invalid function parameters
   */
  MTA_INVALID_PARAMETER_ERROR = 1,
  /**
   * Status code indicating I/O errors
   */
  MTA_IO_ERROR = 2,
  /**
   * Status code indicating serialization/deserialization errors
   */
  MTA_SERIALIZATION_ERROR = 3,
  /**
   * Status code indicating errors that come from callbacks provided by the user.
   * The error message and arbitrary data can be stored using `mta_set_last_error`,
   * and retrieved using `mta_last_error`.
   */
  MTA_CALLBACK_ERROR = 254,
  /**
   * Status code used when there is an internal error
   */
  MTA_INTERNAL_ERROR = 255,
} mta_status_t;

/**
 * TODO
 */
typedef enum mta_system_data_kind {
  MTA_SYSTEM_DATA_TYPES = 0,
  MTA_SYSTEM_DATA_POSITIONS = 1,
  MTA_SYSTEM_DATA_CELL = 2,
  MTA_SYSTEM_DATA_PBC = 3,
} mta_system_data_kind;

/**
 * TODO
 */
typedef struct mta_system_t mta_system_t;

/**
 * An heap-allocated UTF-8 string passed across the C API boundary.
 *
 * This is used whenever a C API function or callback needs to return a string.
 *
 * A null pointer represents an absent or empty string. Use `mta_string_create`
 * to allocate, `mta_string_free` to release, and `mta_string_view` to get a
 * pointer to the inner C string.
 */
typedef mta_opaque_string_t *mta_string_t;

/**
 * A model that computes physical properties of atomistic systems.
 *
 * `mta_model_t` is a small virtual table: `data` holds the model's own state,
 * and the function pointers describe what the model can do. A model is usually
 * produced by a plugin's `load_model` callback (see `mta_load_model`) and then
 * executed with `mta_execute_model`.
 *
 * Every callback receives `data` as its first argument. metatomic treats
 * `data` as opaque and only hands it back to the callbacks. Callbacks should
 * report any error by saving it with `mta_set_last_error` and returning a
 * non-success `mta_status_t`.
 */
typedef struct mta_model_t {
  /**
   * Opaque pointer to the model's internal state
   *
   * Its layout and meaning are private to the model implementation. It is
   * initialized by whoever creates the model (e.g. a plugin's `load_model`)
   * and released by `unload`.
   */
  void *data;
  /**
   * Release the resources owned by `model_data`
   *
   * Called exactly once when the model is no longer needed. May be `NULL` if
   * the model owns no resources.
   *
   * @param model_data the model's `data` pointer
   * @return `MTA_SUCCESS` on success, another status code on error
   */
  enum mta_status_t (*unload)(void *model_data);
  /**
   * Get metadata describing the model (name, authors, references, ...) as a
   * JSON string.
   *
   * @verbatim embed:rst:leading-asterisk
   * The expected JSON structure is documented in :ref:`core-json-model-metadata`.
   * @endverbatim
   *
   * @param model_data the model's `data` pointer
   * @param metadata_json output string, set to a JSON-serialized
   *     `ModelMetadata` object. The
   *     caller takes ownership and must free it with `mta_string_free`.
   * @return `MTA_SUCCESS` on success, another status code on error
   */
  enum mta_status_t (*metadata)(const void *model_data, mta_string_t *metadata_json);
  /**
   * List the outputs this model is able to compute as a JSON string.
   *
   * @verbatim embed:rst:leading-asterisk
   * The expected JSON structure for each output is documented in :ref:`core-json-quantity`.
   * @endverbatim
   *
   * @param model_data the model's `data` pointer
   * @param outputs_json output string, set to a JSON array of `Quantity`
   *     objects, one per supported output. The caller takes ownership and
   *     must free it with `mta_string_free`.
   * @return `MTA_SUCCESS` on success, another status code on error
   */
  enum mta_status_t (*supported_outputs)(const void *model_data, mta_string_t *outputs_json);
  /**
   * List the pair lists (neighbor lists) the model needs as input as a JSON
   * string.
   *
   * @verbatim embed:rst:leading-asterisk
   *
   * The engine is expected to compute these and attach them to every system
   * with :c:func:`mta_system_add_pairs` before calling
   * :c:func:`mta_execute_model`.
   *
   * The expected JSON structure for each pair list is documented in :ref:`core-json-pair-options`.
   *
   * @endverbatim
   *
   * @param model_data the model's `data` pointer
   * @param pair_options_json output string, set to a JSON array of
   *     `PairListOptions` objects. The caller takes ownership and must
   *     free it with `mta_string_free`.
   * @return `MTA_SUCCESS` on success, another status code on error
   */
  enum mta_status_t (*requested_pair_lists)(const void *model_data, mta_string_t *pair_options_json);
  /**
   * List the additional per-system inputs the model needs as a JSON string.
   *
   * @verbatim embed:rst:leading-asterisk
   *
   * These correspond to custom data the engine should attach to every system
   * with :c:func:`mta_system_add_custom_data` before execution.
   *
   * The expected JSON structure for each input is documented in :ref:`core-json-quantity`.
   *
   * @endverbatim
   *
   * @param model_data the model's `data` pointer
   * @param inputs_json output string, set to a JSON array of `Quantity`
   *     objects, one per requested input. The caller takes ownership and
   *     must free it with `mta_string_free`.
   * @return `MTA_SUCCESS` on success, another status code on error
   */
  enum mta_status_t (*requested_inputs)(const void *model_data, mta_string_t *inputs_json);
  /**
   * Run the model and compute the requested outputs
   *
   * @verbatim embed:rst:leading-asterisk
   *
   * This performs the model's actual computation. This should not be called
   * directly, but rather through :c:func:`mta_execute_model`, which handles
   * unit conversion and can check inputs and output data for consistency.
   *
   * @endverbatim
   *
   * @param model_data the model's `data` pointer
   * @param systems array of `systems_count` systems to run the model on
   * @param systems_count number of entries in `systems`
   * @param selected_atoms optional labels selecting the subset of atoms to
   *     compute outputs for, or `NULL` to use all atoms. When set, it has the
   *     dimensions `"system"` and `"atom"` holding 0-based indices.
   * @param requested_outputs_json JSON string containing an array of
   *     `Quantity`, one for each output the model should produce
   * @param outputs array of `outputs_count` tensor maps to fill, one per
   *     requested output and in the same order
   * @param outputs_count number of entries in `outputs`, must equal
   *     `requested_outputs_count`
   * @return `MTA_SUCCESS` on success, another status code on error
   */
  enum mta_status_t (*execute_inner)(void *model_data,
                                     const struct mta_system_t *const *systems,
                                     uintptr_t systems_count,
                                     const mts_labels_t *selected_atoms,
                                     const char *requested_outputs_json,
                                     mts_tensormap_t **outputs,
                                     uintptr_t outputs_count);
} mta_model_t;

/**
 * TODO
 */
typedef struct mta_plugin_t {
  /**
   * TODO
   */
  const char *name;
  /**
   * TODO
   */
  enum mta_status_t (*load_model)(const char *load_from,
                                  const char *options_json,
                                  struct mta_model_t *model);
} mta_plugin_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Get last error message that was created on the current thread.
 */
enum mta_status_t mta_last_error(const char **message, const char **origin, void **data);

/**
 * Set last error message for the current thread.
 */
enum mta_status_t mta_set_last_error(const char *message,
                                     const char *origin,
                                     void *data,
                                     void (*data_deleter)(void*));

/**
 * Get the runtime version of the metatomic library as a string.
 *
 * This version follows the `<major>.<minor>.<patch>[-<dev>]` format.
 */
const char *mta_version(void);

/**
 * Allocate a new `mta_string_t` by copying the null-terminated C string
 * `string`.
 *
 * The returned string must be freed with `mta_string_free`.
 *
 * @param string A pointer to a null-terminated C string. Must not be null.
 * @return A new `mta_string_t` containing a copy of `string`, or null if an
 *     error occurred. You can check the error with `mta_last_error`.
 */
mta_string_t mta_string_create(const char *string);

/**
 * Free a `mta_string_t` previously created by `mta_string_create`.
 *
 * @param string A `mta_string_t` to free. Can be null, in which case this function is a no-op.
 */
void mta_string_free(mta_string_t string);

/**
 * Return a pointer to the null-terminated string data inside `string`.
 *
 * The pointer is valid only for the lifetime of `string`.
 *
 * @param string A `mta_string_t` containing the string to view. Must not be null.
 * @return A pointer to the null-terminated C string inside `string`
 */
const char *mta_string_view(mta_string_t string);

/**
 * Get the multiplicative conversion factor to use to convert from
 * `from_unit` to `to_unit`. Both units are parsed as expressions (e.g.
 * "kJ/mol/A^2", "(eV*u)^(1/2)") and their dimensions must match.
 *
 * Unit expressions are built from base units combined with `*`, `/`, `^`,
 * and parentheses. Unit lookup is case-insensitive, and whitespace is
 * ignored. For example:
 *
 * - `"kJ/mol"` -- energy per mole
 * - `"eV/Angstrom^3"` -- pressure
 * - `"(eV*u)^(1/2)"` -- momentum (fractional powers)
 * - `"Hartree/Bohr"` -- force in atomic units
 *
 * @param from_unit A null-terminated C string containing the unit to convert from.
 * @param to_unit A null-terminated C string containing the unit to convert to.
 * @param conversion A pointer to a `double` where the conversion factor will be stored.
 * @return The status code of the operation. If this code is not `MTA_SUCCESS`,
 *     you can get more details about the error with `mta_last_error`.
 */
enum mta_status_t mta_unit_conversion_factor(const char *from_unit,
                                             const char *to_unit,
                                             double *conversion);

/**
 * TODO
 */
enum mta_status_t mta_system_create(const char *length_unit,
                                    DLManagedTensorVersioned *types,
                                    DLManagedTensorVersioned *positions,
                                    DLManagedTensorVersioned *cell,
                                    DLManagedTensorVersioned *pbc,
                                    struct mta_system_t **system);

/**
 * TODO
 */
enum mta_status_t mta_system_free(struct mta_system_t *system);

/**
 * TODO
 */
enum mta_status_t mta_system_size(const struct mta_system_t *system, uintptr_t *size);

/**
 * TODO
 */
enum mta_status_t mta_system_get_data(const struct mta_system_t *system,
                                      enum mta_system_data_kind request,
                                      DLManagedTensorVersioned **data);

/**
 * TODO
 */
enum mta_status_t mta_system_get_length_unit(const struct mta_system_t *system,
                                             mta_string_t *length_unit);

/**
 * TODO
 */
enum mta_status_t mta_system_add_pairs(struct mta_system_t *system,
                                       const char *options,
                                       mts_block_t *pairs);

/**
 * TODO
 */
enum mta_status_t mta_system_get_pairs(const struct mta_system_t *system,
                                       const char *options,
                                       const mts_block_t **pairs);

/**
 * TODO
 */
enum mta_status_t mta_system_known_pairs(const struct mta_system_t *system,
                                         mta_string_t *pairs_options);

/**
 * TODO
 */
enum mta_status_t mta_system_add_custom_data(struct mta_system_t *system,
                                             const char *name,
                                             mts_tensormap_t *data);

/**
 * TODO
 */
enum mta_status_t mta_system_get_custom_data(const struct mta_system_t *system,
                                             const char *name,
                                             const mts_tensormap_t **data);

/**
 * TODO
 */
enum mta_status_t mta_system_known_custom_data(const struct mta_system_t *system,
                                               mta_string_t *names);

/**
 * Execute a model to compute the requested outputs for a set of systems
 *
 * This is the main entry point to run a model loaded through the C API. It
 * validates the arguments and delegates the computation to the model's
 * `execute_inner` callback.
 *
 * @param model the model to execute
 * @param systems array of `systems_count` systems to run the model on
 * @param systems_count number of entries in `systems`
 * @param selected_atoms optional labels selecting the subset of atoms to
 *     compute outputs for, or `NULL` to use all atoms
 * @param requested_outputs_json JSON string containing an array of
 *     `Quantity`, one for each output the model should produce
 * @param check_consistency if `true`, run additional checks on the
 *     inputs and on the data produced by the model
 * @param outputs array of `outputs_count` tensor maps to fill, one per
 *     requested output and in the same order. The caller takes ownership of
 *     the returned tensor maps.
 * @param outputs_count number of entries in `outputs`, must equal
 *     `requested_outputs_count`
 * @return `MTA_SUCCESS` on success, another status code on error (the message
 *     is available through `mta_last_error`)
 */
enum mta_status_t mta_execute_model(struct mta_model_t model,
                                    const struct mta_system_t *const *systems,
                                    uintptr_t systems_count,
                                    const mts_labels_t *selected_atoms,
                                    const char *requested_outputs_json,
                                    bool check_consistency,
                                    mts_tensormap_t **outputs,
                                    uintptr_t outputs_count);

/**
 * Render model metadata as a human-readable string
 *
 * @param metadata a JSON-serialized `ModelMetadata` object as produced by a
 *     model's `metadata` callback. Must not be null.
 * @param printed output string, set to a human-readable rendering of the
 *     metadata. The caller takes ownership and must free it with
 *     `mta_string_free`.
 * @return `MTA_SUCCESS` on success, another status code on error
 */
enum mta_status_t mta_format_metadata(const char *metadata, mta_string_t *printed);

/**
 * TODO
 */
void mta_register_plugin(struct mta_plugin_t plugin);

/**
 * TODO
 */
enum mta_status_t mta_load_plugin(const char *path);

/**
 * TODO
 */
enum mta_status_t mta_load_model(const char *plugin_name,
                                 const char *load_from,
                                 const char *options_json,
                                 struct mta_model_t *model);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* METATOMIC_H */
