# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - cmake
  tools:
    # Set the version of Python and other tools we need
    python: "3.12"
    rust: "1.75"
  jobs:
    post_install:
      # install metatensor-torch with the CPU version of PyTorch we can not use
      # the `python` section below since it does not allow to specify
      # `--extra-index-url`
      - pip install --extra-index-url https://download.pytorch.org/whl/cpu python/metatensor-torch
      - pip install python/metatensor-learn

    post_build:
      - cargo rustdoc --package metatensor -- --html-before-content docs/src/core/reference/rust/backlink.html
      - rm -rf $READTHEDOCS_OUTPUT/html/core/reference/rust/
      - cp -r target/doc/ $READTHEDOCS_OUTPUT/html/core/reference/rust/
      - cp docs/src/core/reference/rust/index.html $READTHEDOCS_OUTPUT/html/core/reference/rust/


# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/src/conf.py

# Declare the Python requirements required to build the docs
python:
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .
