[build-system]
requires = [
    "setuptools >=44",
    "wheel >=0.36",
    "cmake",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv:tests]
# skip install to avoid rebuilding the world, instead build the wheel and
# install it manually (see below)
skip_install = True
passenv =
    EQUISTORE_BUILD_TYPE
    RUSTUP_HOME
    CARGO*

allowlist_externals =
    bash

deps =
    discover
    numpy

commands =
    python setup.py --quiet bdist_wheel
    bash -c "pip install --force-reinstall --no-deps ./dist/equistore-*.whl"
    discover -p "*.py" -s python/tests

[testenv:lint]
skip_install = True
passenv =
    EQUISTORE_BUILD_TYPE
    RUSTUP_HOME
    CARGO*

deps =
    black
    flake8

commands =
    black --check python
    flake8 --max-line-length=88 --ignore=E203 python
"""
