[build-system]
requires = [
    "setuptools >=44",
    "wheel >=0.36",
    "cmake",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv:tests]
# skip install to avoid rebuilding the world, do the install with setup.py
# instead of pip below
skip_install = True
passenv =
    EQUISTORE_BUILD_TYPE
    RUSTUP_HOME
    CARGO*

deps =
    discover
    numpy

commands =
    python setup.py --quiet install
    discover -p "*.py" -s tests/python

[testenv:lint]
skip_install = True
passenv =
    EQUISTORE_BUILD_TYPE
    RUSTUP_HOME
    CARGO*

deps =
    black
    flake8

commands =
    black --check equistore --extend-exclude equistore/_c_api.py
    flake8 --max-line-length=88 --ignore=E203 equistore
"""
