// A metatomic plugin loading models defined in Python scripts.
//
// The script given to `mta_load_model` must define a `model` variable, which is
// an instance of `metatomic.BaseModel`.
//
// This plugin does not link to libpython. Instead, it uses the Python
// interpreter already running in the current process (if any), or finds the
// Python the user has active (`METATOMIC_PYTHON`, virtual environments, conda
// environments, or `PATH`), and starts it inside the current process. All the
// Python functions are found at runtime, so the same plugin works with all
// Python versions >= 3.10.
//
// Known limitations:
// - the engine and the Python package must use the same shared libmetatomic.
//   The Python package re-uses the libmetatomic already loaded in the process
//   if any, but this does not work if the engine links statically to metatomic;
// - if Python is already initialized in the process, we use it as-is, without
//   changing `sys.path`;

#if defined(__linux__) && !defined(_GNU_SOURCE)
// for RTLD_DEFAULT
#define _GNU_SOURCE
#endif

#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>

#include <mutex>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <psapi.h>
#else
#include <dlfcn.h>
#endif

#include <metatomic.h>

static const char* PLUGIN_NAME = "python";

// Source code of find-python.py, generated by CMake. This script is executed
// with the user's Python to find how to start Python in the current process.
static const unsigned char FIND_PYTHON_HEX[] = {
#include "find-python.py.inc"
};
static const char* FIND_PYTHON_CODE = reinterpret_cast<const char*>(FIND_PYTHON_HEX);

// Markers for the first line of output of the probe script
static const std::string PROBE_SUCCESS = "metatomic-find-python-success";
static const std::string PROBE_ERROR = "metatomic-find-python-error: ";

// This must be the same as the origin used in `metatomic._status`, so that
// Python engines get the original exception back from `mta_last_error`.
static const char* PYTHON_EXCEPTION_ORIGIN = "Python exception";

/******************************************************************************/
/*                          Platform-specific helpers                         */
/******************************************************************************/

#ifdef _WIN32
using library_t = HMODULE;

static void* get_symbol(library_t library, const char* name) {
    return reinterpret_cast<void*>(GetProcAddress(library, name));
}

static std::wstring utf8_to_wide(const std::string& string) {
    if (string.empty()) {
        return std::wstring();
    }

    auto size = MultiByteToWideChar(CP_UTF8, 0, string.data(), static_cast<int>(string.size()), nullptr, 0);
    auto result = std::wstring(static_cast<size_t>(size), L'\0');
    MultiByteToWideChar(CP_UTF8, 0, string.data(), static_cast<int>(string.size()), &result[0], size);
    return result;
}

static std::string wide_to_utf8(const wchar_t* string) {
    auto size = WideCharToMultiByte(CP_UTF8, 0, string, -1, nullptr, 0, nullptr, nullptr);
    if (size <= 1) {
        return std::string();
    }
    // `size` includes the NULL terminator
    auto result = std::string(static_cast<size_t>(size - 1), '\0');
    WideCharToMultiByte(CP_UTF8, 0, string, -1, &result[0], size, nullptr, nullptr);
    return result;
}
#else
using library_t = void*;

static void* get_symbol(library_t library, const char* name) {
    return dlsym(library, name);
}
#endif

/// Get the value of an environment variable, or `std::nullopt` if the variable
/// is not set
static std::optional<std::string> get_env(const char* name) {
#ifdef _WIN32
    const auto* value = _wgetenv(utf8_to_wide(name).c_str());
    if (value == nullptr) {
        return std::nullopt;
    }
    return wide_to_utf8(value);
#else
    const auto* value = std::getenv(name);
    if (value == nullptr) {
        return std::nullopt;
    }
    return std::string(value);
#endif
}

/// Set (or unset if `value` is `std::nullopt`) an environment variable
static void set_env(const char* name, const std::optional<std::string>& value) {
#ifdef _WIN32
    auto wide_name = utf8_to_wide(name);
    auto wide_value = utf8_to_wide(value.value_or(""));
    // setting an empty value removes the variable. We update both the C
    // runtime environment (used by Python and `_wpopen`) and the process
    // environment.
    _wputenv_s(wide_name.c_str(), wide_value.c_str());
    SetEnvironmentVariableW(wide_name.c_str(), value ? wide_value.c_str() : nullptr);
#else
    if (value) {
        setenv(name, value->c_str(), 1);
    } else {
        unsetenv(name);
    }
#endif
}

namespace {
/// Set an environment variable for the lifetime of this object, restoring the
/// previous value when it is destroyed.
class ScopedEnv {
public:
    ScopedEnv(const char* name, const std::string& value): name_(name), old_value_(get_env(name)) {
        set_env(name_, value);
    }

    ~ScopedEnv() {
        set_env(name_, old_value_);
    }

    ScopedEnv(const ScopedEnv&) = delete;
    ScopedEnv& operator=(const ScopedEnv&) = delete;

private:
    const char* name_;
    std::optional<std::string> old_value_;
};
} // namespace


/******************************************************************************/
/*                     Minimal declarations for Python                        */
/******************************************************************************/

namespace {
// We only use pointers to Python objects, so we don't need the full definition
struct PyObject;
using Py_ssize_t = std::ptrdiff_t;
// `PyGILState_STATE` is an enum
using PyGILState_STATE = int;

/// All the functions we need from libpython, they will be dynamically loaded at
/// runtime to avoid linking to a specific Python version.
struct PythonApi {
    int (*Py_IsInitialized)() = nullptr;
    void (*Py_InitializeEx)(int) = nullptr;
    void* (*PyEval_SaveThread)() = nullptr;
    PyGILState_STATE (*PyGILState_Ensure)() = nullptr;
    void (*PyGILState_Release)(PyGILState_STATE) = nullptr;
    int (*PyRun_SimpleStringFlags)(const char*, void*) = nullptr;

    PyObject* (*PyImport_ImportModule)(const char*) = nullptr;
    PyObject* (*PyObject_CallMethod)(PyObject*, const char*, const char*, ...) = nullptr;
    PyObject* (*PyObject_GetAttrString)(PyObject*, const char*) = nullptr;
    PyObject* (*PyDict_GetItemString)(PyObject*, const char*) = nullptr;
    int (*PyObject_IsInstance)(PyObject*, PyObject*) = nullptr;
    void* (*PyLong_AsVoidPtr)(PyObject*) = nullptr;
    void (*Py_IncRef)(PyObject*) = nullptr;
    void (*Py_DecRef)(PyObject*) = nullptr;

    PyObject* (*PyErr_Occurred)() = nullptr;
    void (*PyErr_Clear)() = nullptr;
    PyObject* (*PyObject_Str)(PyObject*) = nullptr;
    const char* (*PyUnicode_AsUTF8AndSize)(PyObject*, Py_ssize_t*) = nullptr;
    // only available in Python >= 3.12
    PyObject* (*PyErr_GetRaisedException)() = nullptr;
    // used for Python < 3.12
    void (*PyErr_Fetch)(PyObject**, PyObject**, PyObject**) = nullptr;
    void (*PyErr_NormalizeException)(PyObject**, PyObject**, PyObject**) = nullptr;
    int (*PyException_SetTraceback)(PyObject*, PyObject*) = nullptr;
};
} // namespace

static PythonApi PY;

template <typename T>
static bool load_symbol(library_t library, const char* name, T& function) {
    function = reinterpret_cast<T>(get_symbol(library, name));
    return function != nullptr;
}

/// Try to load all the functions we need from `library`, returning
/// `std::nullopt` if any of them is missing.
static std::optional<PythonApi> load_python_functions(library_t library) {
    auto api = PythonApi();

    #define LOAD(name) if (!load_symbol(library, #name, api.name)) { return std::nullopt; }

    LOAD(Py_IsInitialized);
    LOAD(Py_InitializeEx);
    LOAD(PyEval_SaveThread);
    LOAD(PyGILState_Ensure);
    LOAD(PyGILState_Release);
    LOAD(PyRun_SimpleStringFlags);
    LOAD(PyImport_ImportModule);
    LOAD(PyObject_CallMethod);
    LOAD(PyObject_GetAttrString);
    LOAD(PyDict_GetItemString);
    LOAD(PyObject_IsInstance);
    LOAD(PyLong_AsVoidPtr);
    LOAD(Py_IncRef);
    LOAD(Py_DecRef);
    LOAD(PyErr_Occurred);
    LOAD(PyErr_Clear);
    LOAD(PyObject_Str);
    LOAD(PyUnicode_AsUTF8AndSize);

    if (!load_symbol(library, "PyErr_GetRaisedException", api.PyErr_GetRaisedException)) {
        LOAD(PyErr_Fetch);
        LOAD(PyErr_NormalizeException);
        LOAD(PyException_SetTraceback);
    }

    #undef LOAD

    return api;
}

/******************************************************************************/
/*                              Error handling                                */
/******************************************************************************/

namespace {
/// Error in the plugin itself, reported with `MTA_INVALID_PARAMETER_ERROR`
class PluginError: public std::runtime_error {
public:
    using std::runtime_error::runtime_error;
};

/// Marker exception, thrown when a Python function failed and a Python
/// exception is set. This must only be thrown and caught with the GIL held.
struct PythonError {};
} // namespace

/// Data deleter for `mta_set_last_error`, releasing a Python exception
static void python_exception_deleter(void* exception) {
    auto state = PY.PyGILState_Ensure();
    PY.Py_DecRef(static_cast<PyObject*>(exception));
    PY.PyGILState_Release(state);
}

/// Move the current Python exception into the last metatomic error. This must
/// be called with the GIL held, and a Python exception set.
static mta_status_t set_error_from_python() {
    PyObject* exception = nullptr;
    if (PY.PyErr_GetRaisedException != nullptr) {
        exception = PY.PyErr_GetRaisedException();
    } else {
        PyObject* type = nullptr;
        PyObject* traceback = nullptr;
        PY.PyErr_Fetch(&type, &exception, &traceback);
        PY.PyErr_NormalizeException(&type, &exception, &traceback);
        if (exception != nullptr && traceback != nullptr) {
            PY.PyException_SetTraceback(exception, traceback);
        }
        if (type != nullptr) {
            PY.Py_DecRef(type);
        }
        if (traceback != nullptr) {
            PY.Py_DecRef(traceback);
        }
    }

    if (exception == nullptr) {
        mta_set_last_error("unknown Python error", PLUGIN_NAME, nullptr, nullptr);
        return MTA_MODEL_ERROR;
    }

    // Get `str(object)` as a C++ string, or an empty string on error
    auto to_string = [](PyObject* object) {
        auto result = std::string();
        if (object == nullptr) {
            return result;
        }

        auto* string = PY.PyObject_Str(object);
        if (string != nullptr) {
            const auto* utf8 = PY.PyUnicode_AsUTF8AndSize(string, nullptr);
            if (utf8 != nullptr) {
                result = utf8;
            }
            PY.Py_DecRef(string);
        } else {
            result = "<unprintable Python exception>";
        }
        // clear any error from `str(object)`
        PY.PyErr_Clear();
        return result;
    };


    auto class_name = std::string();
    auto* klass = PY.PyObject_GetAttrString(exception, "__class__");
    if (klass != nullptr) {
        auto* name = PY.PyObject_GetAttrString(klass, "__name__");
        class_name = to_string(name);
        if (name != nullptr) {
            PY.Py_DecRef(name);
        }
        PY.Py_DecRef(klass);
    }
    PY.PyErr_Clear();

    auto message = to_string(exception);
    if (message.empty()) {
        message = class_name.empty() ? "<Python exception>" : class_name;
    } else if (!class_name.empty()) {
        message = class_name + ": " + message;
    }

    // the reference to `exception` is transferred to metatomic, and will be
    // released by `python_exception_deleter`
    mta_set_last_error(message.c_str(), PYTHON_EXCEPTION_ORIGIN, exception, python_exception_deleter);
    return MTA_MODEL_ERROR;
}

/******************************************************************************/
/*                           Python helper classes                            */
/******************************************************************************/

namespace {
/// RAII wrapper around an owned reference to a Python object. This must only
/// be created and destroyed while holding the GIL.
class PyRef {
public:
    PyRef() = default;

    /// Take ownership of `object`, throwing `PythonError` if it is NULL
    static PyRef check(PyObject* object) {
        if (object == nullptr) {
            throw PythonError{};
        }
        return PyRef(object);
    }

    ~PyRef() {
        if (object_ != nullptr) {
            PY.Py_DecRef(object_);
        }
    }

    PyRef(const PyRef&) = delete;
    PyRef& operator=(const PyRef&) = delete;

    PyRef(PyRef&& other) noexcept: object_(std::exchange(other.object_, nullptr)) {}
    PyRef& operator=(PyRef&& other) noexcept {
        std::swap(object_, other.object_);
        return *this;
    }

    PyObject* get() const {
        return object_;
    }

private:
    explicit PyRef(PyObject* object): object_(object) {}

    PyObject* object_ = nullptr;
};

/// RAII guard holding the GIL
class GilGuard {
public:
    GilGuard(): state_(PY.PyGILState_Ensure()) {}
    ~GilGuard() {
        PY.PyGILState_Release(state_);
    }

    GilGuard(const GilGuard&) = delete;
    GilGuard& operator=(const GilGuard&) = delete;

private:
    PyGILState_STATE state_;
};
} // namespace


/******************************************************************************/
/*                        Finding & starting Python                           */
/******************************************************************************/

/// Check if libpython is already loaded in the current process, and get the
/// Python functions from there if it is.
static std::optional<PythonApi> find_python_in_process() {
#ifdef _WIN32
    auto modules = std::vector<HMODULE>(1024);
    DWORD needed = 0;
    auto process = GetCurrentProcess();
    auto size = static_cast<DWORD>(modules.size() * sizeof(HMODULE));
    if (!EnumProcessModules(process, modules.data(), size, &needed)) {
        return std::nullopt;
    }

    if (needed > size) {
        modules.resize(needed / sizeof(HMODULE));
        size = static_cast<DWORD>(modules.size() * sizeof(HMODULE));
        if (!EnumProcessModules(process, modules.data(), size, &needed)) {
            return std::nullopt;
        }
    }
    modules.resize(needed / sizeof(HMODULE));

    for (auto module: modules) {
        auto api = load_python_functions(module);
        if (api) {
            return api;
        }
    }
    return std::nullopt;
#else
    return load_python_functions(RTLD_DEFAULT);
#endif
}

namespace {
/// Information about a Python installation, extracted with find-python.py
struct PythonInfo {
    std::string executable;
    std::string libpython;
    std::string home;
    std::string setup_code;
};
} // namespace

/// Read the full output of `pipe`, removing '\r' from Windows line endings
static std::string read_all(FILE* pipe) {
    auto output = std::string();
    char buffer[4096];
    size_t count = 0;
    while ((count = std::fread(buffer, 1, sizeof(buffer), pipe)) > 0) {
        for (size_t i = 0; i < count; i++) {
            if (buffer[i] != '\r') {
                output.push_back(buffer[i]);
            }
        }
    }
    return output;
}

/// Run the find-python.py script with the given Python executable, adding
/// `arguments` (if any) before the script. Returns `std::nullopt` if the
/// executable could not be run, and throws a `PluginError` if the script
/// reported an error.
static std::optional<PythonInfo> run_find_python(
    const std::string& python,
    const std::string& arguments
) {
    // The script source is given through an environment variable to avoid any
    // issue with quoting or command line length limits
    auto probe = ScopedEnv(
        "METATOMIC_FIND_PYTHON_CODE",
        FIND_PYTHON_CODE
    );
    const auto* code = "import os; exec(os.environ['METATOMIC_FIND_PYTHON_CODE'])";

#ifdef _WIN32
    // cmd.exe removes the outer quotes, so we need to add an additional pair
    auto command = "\"\"" + python + "\" " + arguments + " -c \"" + code + "\" 2>NUL\"";
    auto* pipe = _wpopen(utf8_to_wide(command).c_str(), L"rb");
#else
    auto command = "\"" + python + "\" " + arguments + " -c \"" + code + "\" 2>/dev/null";
    auto* pipe = popen(command.c_str(), "r");
#endif

    if (pipe == nullptr) {
        return std::nullopt;
    }

    auto output = read_all(pipe);
#ifdef _WIN32
    auto status = _pclose(pipe);
#else
    auto status = pclose(pipe);
#endif

    auto lines = std::vector<std::string>();
    size_t start = 0;
    while (lines.size() < 4) {
        auto end = output.find('\n', start);
        if (end == std::string::npos) {
            break;
        }
        lines.push_back(output.substr(start, end - start));
        start = end + 1;
    }

    auto display = arguments.empty() ? python : python + " " + arguments;
    if (!lines.empty() && lines[0].compare(0, PROBE_ERROR.size(), PROBE_ERROR) == 0) {
        throw PluginError(
            "can not use the Python interpreter at '" + display + "': " +
            lines[0].substr(PROBE_ERROR.size())
        );
    }

    if (status != 0 || lines.empty() || lines[0] != PROBE_SUCCESS) {
        return std::nullopt;
    }

    if (lines.size() != 4 || start >= output.size()) {
        throw PluginError("invalid output from the Python probe script for '" + display + "'");
    }

    auto info = PythonInfo();
    info.executable = lines[1];
    info.libpython = lines[2];
    info.home = lines[3];
    info.setup_code = output.substr(start);
    return info;
}

/// Find the Python the user has active, and extract information about it.
static PythonInfo find_user_python() {
    auto explicit_python = get_env("METATOMIC_PYTHON");
    if (explicit_python && !explicit_python->empty()) {
        auto info = run_find_python(*explicit_python, "");
        if (!info) {
            throw PluginError(
                "failed to run the Python interpreter at '" + *explicit_python +
                "' (from METATOMIC_PYTHON)"
            );
        }
        return *info;
    }

    struct Candidate {
        // implicit, so a path can be used directly as a candidate
        Candidate(std::string executable_, std::string arguments_ = std::string()):
            executable(std::move(executable_)),
            arguments(std::move(arguments_))
        {}

        std::string executable;
        std::string arguments;
    };

    // candidates, in order of preference
    auto candidates = std::vector<Candidate>();

    auto virtual_env = get_env("VIRTUAL_ENV");
    if (virtual_env && !virtual_env->empty()) {
#ifdef _WIN32
        candidates.emplace_back(*virtual_env + "\\Scripts\\python.exe");
#else
        candidates.emplace_back(*virtual_env + "/bin/python");
#endif
    }

    auto conda_prefix = get_env("CONDA_PREFIX");
    if (conda_prefix && !conda_prefix->empty()) {
#ifdef _WIN32
        candidates.emplace_back(*conda_prefix + "\\python.exe");
#else
        candidates.emplace_back(*conda_prefix + "/bin/python");
#endif
    }

#ifdef _WIN32
    // Python installs on Windows (python.org, venv, conda) only provide
    // `python.exe`, not `python3.exe`.
    candidates.emplace_back("python");
    // The `py` launcher is installed by python.org, even when Python itself is
    // not added to the PATH.
    candidates.emplace_back("py", "-3");
#else
    candidates.emplace_back("python3");
    candidates.emplace_back("python");
#endif

    for (const auto& candidate: candidates) {
        auto info = run_find_python(candidate.executable, candidate.arguments);
        if (info) {
            return *info;
        }
    }

    throw PluginError(
        "could not find a Python interpreter, please activate a virtual "
        "environment, add python to the PATH or set METATOMIC_PYTHON environment variable"
    );
}

/// Load libpython from `info`, and initialize the interpreter
static void start_python(const PythonInfo& info) {
#ifdef _WIN32
    auto library = LoadLibraryExW(utf8_to_wide(info.libpython).c_str(), nullptr, LOAD_WITH_ALTERED_SEARCH_PATH);
    if (library == nullptr) {
        throw PluginError(
            "failed to load libpython from '" + info.libpython + "' (error " +
            std::to_string(GetLastError()) + ")"
        );
    }
#else
    // RTLD_GLOBAL is required for Python extension modules (numpy, ...), which
    // expect Python symbols to be available globally.
    auto* library = dlopen(info.libpython.c_str(), RTLD_NOW | RTLD_GLOBAL);
    if (library == nullptr) {
        throw PluginError("failed to load libpython from '" + info.libpython + "': " + dlerror());
    }
#endif

    auto api = load_python_functions(library);
    if (!api) {
        throw PluginError("'" + info.libpython + "' does not contain all the expected Python functions");
    }
    PY = *api;

    if (PY.Py_IsInitialized() == 0) {
        {
            auto home = ScopedEnv("PYTHONHOME", info.home);
            // 0 to skip the installation of signal handlers
            PY.Py_InitializeEx(0);
        }

        if (PY.Py_IsInitialized() == 0) {
            throw PluginError("failed to initialize Python from '" + info.libpython + "'");
        }

        auto setup_status = PY.PyRun_SimpleStringFlags(info.setup_code.c_str(), nullptr);

        // release the GIL, so any thread can acquire it with PyGILState_Ensure
        PY.PyEval_SaveThread();

        if (setup_status != 0) {
            // the error was printed by Python
            throw PluginError(
                "failed to setup sys.path for Python at '" + info.executable +
                "', see the error above"
            );
        }
    }
}

/// Make sure Python is loaded and initialized. This is safe to call multiple
/// times and from multiple threads.
static void ensure_python() {
    static std::mutex MUTEX;
    static bool PYTHON_READY = false;

    auto lock = std::lock_guard<std::mutex>(MUTEX);
    if (PYTHON_READY) {
        return;
    }

    auto api = find_python_in_process();
    if (api && (api->Py_IsInitialized() != 0)) {
        // Python is already running (e.g. the engine is written in Python),
        // use it as-is
        PY = *api;
    } else {
        start_python(find_user_python());
    }

    PYTHON_READY = true;
}

/******************************************************************************/
/*                              Model loading                                 */
/******************************************************************************/

/// `unload` callback for models loaded by this plugin
static mta_status_t python_model_unload(void* model_data) {
    auto gil = GilGuard();
    PY.Py_DecRef(static_cast<PyObject*>(model_data));
    return MTA_SUCCESS;
}

/// Check that `options_json` is NULL or an empty JSON object
static bool empty_options(const char* options_json) {
    if (options_json == nullptr) {
        return true;
    }

    auto options = std::string(options_json);
    auto is_space = [](char c) { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; };

    auto compact = std::string();
    for (auto c: options) {
        if (!is_space(c)) {
            compact.push_back(c);
        }
    }
    return compact == "{}" || compact.empty();
}

/// Load the model defined in the script at `path`. This must be called with
/// the GIL held, and throws `PythonError` if a Python function fails.
static void load_python_model(const char* path, mta_model_t* model) {
    auto runpy = PyRef::check(PY.PyImport_ImportModule("runpy"));

    // the script is executed with `__name__ == "<run_path>"`
    auto globals = PyRef::check(PY.PyObject_CallMethod(runpy.get(), "run_path", "s", path));

    // borrowed reference, kept alive by `globals`
    auto* py_model = PY.PyDict_GetItemString(globals.get(), "model");
    if (py_model == nullptr) {
        throw PluginError(
            "the Python script at '" + std::string(path) +
            "' does not define a 'model' variable"
        );
    }

    auto metatomic = PyRef::check(PY.PyImport_ImportModule("metatomic"));
    auto base_model = PyRef::check(PY.PyObject_GetAttrString(metatomic.get(), "BaseModel"));
    auto external_model = PyRef::check(PY.PyObject_GetAttrString(metatomic.get(), "ExternalModel"));

    auto is_base = PY.PyObject_IsInstance(py_model, base_model.get());
    if (is_base < 0) {
        throw PythonError{};
    }

    auto is_external = PY.PyObject_IsInstance(py_model, external_model.get());
    if (is_external < 0) {
        throw PythonError{};
    }

    if ((is_base == 0) || (is_external != 0)) {
        throw PluginError(
            "the 'model' variable in the Python script at '" + std::string(path) +
            "' must be an instance of metatomic.BaseModel (and not metatomic.ExternalModel)"
        );
    }

    // Get the `mta_model_t` struct created by the Python code, and copy it in
    // the output. The function pointers in this struct are defined at the
    // module level in `metatomic._model._base`, and stay alive for as long as
    // this module is loaded, so we don't need to keep `raw_model` around.
    auto raw_model = PyRef::check(PY.PyObject_CallMethod(py_model, "_as_mta_model_t", nullptr));
    auto ctypes = PyRef::check(PY.PyImport_ImportModule("ctypes"));
    auto address = PyRef::check(PY.PyObject_CallMethod(ctypes.get(), "addressof", "O", raw_model.get()));

    auto* pointer = PY.PyLong_AsVoidPtr(address.get());
    if (pointer == nullptr) {
        if (PY.PyErr_Occurred() != nullptr) {
            throw PythonError{};
        }
        throw PluginError("got a NULL pointer for the model created by Python");
    }

    auto result = mta_model_t{};
    std::memcpy(&result, pointer, sizeof(mta_model_t));
    if (result.data != static_cast<void*>(py_model)) {
        throw PluginError("internal error: unexpected data pointer in the model created by Python");
    }

    // keep the model alive until `unload` is called
    PY.Py_IncRef(py_model);
    result.unload = python_model_unload;

    *model = result;
}

static mta_status_t load_model(const char* load_from, const char* options_json, mta_model_t* model) {
    try {
        if (load_from == nullptr || model == nullptr) {
            mta_set_last_error("got a NULL pointer in load_model", PLUGIN_NAME, nullptr, nullptr);
            return MTA_INVALID_PARAMETER_ERROR;
        }

        auto length = std::strlen(load_from);
        if (length < 3 || std::strcmp(load_from + length - 3, ".py") != 0) {
            // not a Python script, let other plugins try to load this model
            return MTA_UNSUPPORTED_MODEL_ERROR;
        }

        if (!empty_options(options_json)) {
            mta_set_last_error("the Python plugin does not support any options yet", PLUGIN_NAME, nullptr, nullptr);
            return MTA_INVALID_PARAMETER_ERROR;
        }

        ensure_python();

        auto gil = GilGuard();
        try {
            load_python_model(load_from, model);
        } catch (const PythonError&) {
            // this needs to run while we still hold the GIL
            return set_error_from_python();
        }

        return MTA_SUCCESS;
    } catch (const std::exception& e) {
        mta_set_last_error(e.what(), PLUGIN_NAME, nullptr, nullptr);
        return MTA_MODEL_ERROR;
    } catch (...) {
        mta_set_last_error("unknown C++ error in the Python plugin", PLUGIN_NAME, nullptr, nullptr);
        return MTA_MODEL_ERROR;
    }
}

MTA_REGISTER_PLUGIN(register_plugin, {
    mta_plugin_t plugin = {};
    plugin.abi_version = MTA_ABI_VERSION;
    plugin.name = PLUGIN_NAME;
    plugin.load_model = load_model;
    return register_plugin(plugin);
});
