use std::collections::BTreeMap;
use std::ffi::{CStr, CString};
use std::sync::Mutex;

use libloading::Library;
use once_cell::sync::Lazy;

use crate::c_api::{mta_model_t, mta_plugin_t, mta_status_t};
use crate::{Error, Model};

/// ABI version of the metatomic plugin interface.
pub const MTA_ABI_VERSION: i32 = 1;

type PluginAbiVersionFn = unsafe extern "C" fn() -> i32;
type PluginRegisterFn = unsafe extern "C" fn() -> mta_status_t;

static PLUGINS: Lazy<Mutex<Vec<Plugin>>> = Lazy::new(|| Mutex::new(Vec::new()));
static LOADED_LIBRARIES: Lazy<Mutex<Vec<Library>>> = Lazy::new(|| Mutex::new(Vec::new()));

/// A metatomic plugin.
pub struct Plugin(mta_plugin_t);

unsafe impl Send for Plugin {}
unsafe impl Sync for Plugin {}

impl Plugin {
    /// Create a new `Plugin` from the corresponding C API struct.
    pub fn new(c_plugin: mta_plugin_t) -> Self {
        return Self(c_plugin);
    }

    /// Get the plugin name.
    pub fn name(&self) -> &str {
        unsafe {
            return CStr::from_ptr(self.0.name)
                .to_str()
                .expect("invalid UTF-8 in plugin name");
        }
    }

    /// Load a model with this plugin.
    pub fn load_model(
        &self,
        load_from: &str,
        options: BTreeMap<String, String>,
    ) -> Result<Model, Error> {
        let options = options_to_json(&options);
        return self.load_model_json(load_from, &options);
    }

    pub(crate) fn load_model_json(
        &self,
        load_from: &str,
        options_json: &str,
    ) -> Result<Model, Error> {
        let c_load_from = CString::new(load_from)
            .map_err(|_| Error::InvalidParameter("model path contains a NUL byte".into()))?;
        let c_options = CString::new(options_json).map_err(|_| {
            Error::InvalidParameter("model loading options contain a NUL byte".into())
        })?;

        let load_model = self.0.load_model.ok_or_else(|| {
            Error::InvalidParameter(format!(
                "plugin '{}' does not define a load_model callback",
                self.name()
            ))
        })?;

        let mut model = mta_model_t::null();
        let status = unsafe { load_model(c_load_from.as_ptr(), c_options.as_ptr(), &mut model) };
        check_status(status)?;

        return Ok(Model::new(model));
    }

    fn validate(&self) -> Result<(), Error> {
        if self.0.abi_version != MTA_ABI_VERSION {
            return Err(Error::InvalidParameter(format!(
                "can not register plugin '{}': plugin ABI version is {}, but this metatomic library expects {}",
                unsafe { plugin_name_for_error(self.0.name) },
                self.0.abi_version,
                MTA_ABI_VERSION,
            )));
        }

        if self.0.name.is_null() {
            return Err(Error::InvalidParameter(
                "can not register plugin with a NULL name".into(),
            ));
        }

        let name = unsafe { CStr::from_ptr(self.0.name) };
        name.to_str().map_err(|_| {
            Error::InvalidParameter("can not register plugin with a non UTF-8 name".into())
        })?;

        if self.0.load_model.is_none() {
            return Err(Error::InvalidParameter(format!(
                "can not register plugin '{}': missing load_model callback",
                self.name()
            )));
        }

        return Ok(());
    }
}

/// Register a new plugin in the current process.
pub(crate) fn register_plugin(plugin: Plugin) -> Result<(), Error> {
    plugin.validate()?;

    let mut plugins = PLUGINS.lock().expect("plugin registry mutex was poisoned");
    if plugins.iter().any(|existing| existing.name() == plugin.name()) {
        return Err(Error::InvalidParameter(format!(
            "a plugin named '{}' is already registered",
            plugin.name()
        )));
    }

    plugins.push(plugin);
    return Ok(());
}

/// Load a plugin from a shared library.
///
/// The shared library must export the symbols generated by the `MTA_PLUGIN`
/// C macro.
pub fn load_plugin(path: &str) -> Result<(), Error> {
    let library = unsafe { open_library(path)? };

    let abi_version = unsafe {
        let abi_version = library.get::<PluginAbiVersionFn>(b"mta_plugin_abi_version\0").map_err(
            |error| {
                Error::InvalidParameter(format!(
                    "failed to load plugin ABI version symbol from '{}': {}",
                    path, error
                ))
            },
        )?;
        abi_version()
    };

    if abi_version != MTA_ABI_VERSION {
        return Err(Error::InvalidParameter(format!(
            "can not load plugin '{}': plugin ABI version is {}, but this metatomic library expects {}",
            path, abi_version, MTA_ABI_VERSION
        )));
    }

    let status = unsafe {
        let register = library
            .get::<PluginRegisterFn>(b"mta_plugin_register\0")
            .map_err(|error| {
                Error::InvalidParameter(format!(
                    "failed to load plugin registration symbol from '{}': {}",
                    path, error
                ))
            })?;
        register()
    };
    check_status(status)?;

    LOADED_LIBRARIES
        .lock()
        .expect("loaded plugin registry mutex was poisoned")
        .push(library);

    return Ok(());
}

/// Load a model using a registered plugin.
pub fn load_model(
    plugin: Option<&str>,
    load_from: &str,
    options: BTreeMap<String, String>,
) -> Result<Model, Error> {
    let options = options_to_json(&options);
    return load_model_json(plugin, load_from, &options);
}

pub(crate) fn load_model_json(
    plugin_name: Option<&str>,
    load_from: &str,
    options_json: &str,
) -> Result<Model, Error> {
    let plugins = PLUGINS.lock().expect("plugin registry mutex was poisoned");

    if let Some(plugin_name) = plugin_name {
        for plugin in plugins.iter() {
            if plugin.name() == plugin_name {
                return plugin.load_model_json(load_from, options_json);
            }
        }

        return Err(Error::InvalidParameter(format!(
            "no plugin named '{}' is registered",
            plugin_name
        )));
    }

    let mut failures = Vec::new();
    for plugin in plugins.iter() {
        match plugin.load_model_json(load_from, options_json) {
            Ok(model) => return Ok(model),
            Err(error) => failures.push(format!("{}: {}", plugin.name(), error)),
        }
    }

    if plugins.is_empty() {
        return Err(Error::InvalidParameter(
            "no metatomic plugin is registered".into(),
        ));
    }

    return Err(Error::InvalidParameter(format!(
        "no registered plugin could load '{}'; failures: {}",
        load_from,
        failures.join("; ")
    )));
}

fn options_to_json(options: &BTreeMap<String, String>) -> String {
    let mut json = json::JsonValue::new_object();
    for (key, value) in options {
        json[key] = value.clone().into();
    }
    return json.dump();
}

fn check_status(status: mta_status_t) -> Result<(), Error> {
    if status == mta_status_t::MTA_SUCCESS {
        return Ok(());
    }

    return Err(Error::CallbackError);
}

unsafe fn plugin_name_for_error(name: *const std::ffi::c_char) -> String {
    if name.is_null() {
        return "<unknown>".into();
    }

    return CStr::from_ptr(name).to_string_lossy().into_owned();
}

unsafe fn open_library(path: &str) -> Result<Library, Error> {
    return Library::new(path).map_err(|error| {
        Error::Io(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("failed to load plugin '{}': {}", path, error),
        ))
    });
}
