use std::ffi::CStr;
use std::sync::Mutex;

use libloading::Library;
use once_cell::sync::Lazy;

use crate::c_api::{mta_model_t, mta_plugin_t, mta_register_plugin, mta_status_t};
use crate::{Error, Model};

/// ABI version of the metatomic plugin interface.
///
/// This increases anytime the plugin or model C API changes in a non backward
/// compatible way. Plugins compiled with an incompatible ABI version will be
/// rejected at registration time.
pub const MTA_ABI_VERSION: i32 = 1;

/// The list of registered plugins in the current process.
static PLUGINS: Lazy<Mutex<Vec<Plugin>>> = Lazy::new(|| Mutex::new(Vec::new()));
/// Keep the loaded libraries alive for the entire process lifetime, to ensure
/// that the plugin code is not unloaded while it's still in use.
static LIBRARIES: Lazy<Mutex<Vec<Library>>> = Lazy::new(|| Mutex::new(Vec::new()));

pub struct Plugin(mta_plugin_t);

impl Plugin {
    /// Create a new plugin from the C struct
    pub fn new(plugin: mta_plugin_t) -> Result<Plugin, Error> {
        if plugin.name.is_null() {
            return Err(Error::InvalidParameter(
                "can not register plugin: plugin `name` is NULL".into(),
            ));
        }

        let c_str_name = unsafe { CStr::from_ptr(plugin.name) };
        if c_str_name.to_str().is_err() {
            return Err(Error::InvalidParameter(format!(
                "can not register plugin: plugin `name` is not valid UTF-8: {}",
                c_str_name.to_string_lossy()
            )));
        }

        if plugin.load_model.is_none() {
            return Err(Error::InvalidParameter(
                "can not register plugin: plugin `load_model` callback is NULL".into(),
            ));
        }

        if plugin.abi_version != MTA_ABI_VERSION {
            let name = unsafe {
                CStr::from_ptr(plugin.name).to_string_lossy()
            };

            return Err(Error::InvalidParameter(format!(
                "can not register plugin '{}': plugin ABI version is {}, but metatomic expects {}",
                name,
                plugin.abi_version,
                MTA_ABI_VERSION,
            )));
        }

        Ok(Plugin(plugin))
    }

    /// Get the plugin name.
    pub fn name(&self) -> &str {
        unsafe {
            return CStr::from_ptr(self.0.name)
                .to_str()
                .expect("invalid UTF-8 in plugin name");
        }
    }

    /// Try to load a model with this plugin.
    pub fn load_model(
        &self,
        load_from: &CStr,
        options_json: &CStr,
    ) -> Result<Model, Error> {
        let load_model = self.0.load_model.expect("`load_model` is NULL");

        let mut model = mta_model_t::null();
        let status = unsafe {
            load_model(load_from.as_ptr(), options_json.as_ptr(), &mut model)
        };

        if status != mta_status_t::MTA_SUCCESS {
            return Err(Error::CallbackError(status));
        }

        return Ok(Model::new(model));
    }
}

/// Register a new plugin in the current process.
pub fn register_plugin(plugin: Plugin) -> Result<(), Error> {
    let mut plugins = PLUGINS.lock().expect("plugin registry mutex was poisoned");
    if plugins.iter().any(|existing| existing.name() == plugin.name()) {
        return Err(Error::InvalidParameter(format!(
            "a plugin named '{}' is already registered",
            plugin.name()
        )));
    }

    plugins.push(plugin);
    return Ok(());
}

/// Load a plugin from a shared library.
///
/// The shared library must export the symbols generated by the
/// `MTA_REGISTER_PLUGIN` C macro.
pub fn load_plugin(path: &str) -> Result<(), Error> {
    // this needs to be kept in sync with the definition in `MTA_REGISTER_PLUGIN` in build.rs
    type PluginInitFn = unsafe extern "C" fn(abi: i32, data: *mut std::ffi::c_void) -> mta_status_t;

    let library = unsafe { Library::new(path) };

    let library = library.map_err(|error| {
        std::io::Error::other(
            format!("failed to load plugin '{}': {}", path, error),
        )
    })?;

    let status = unsafe {
        let init_plugin = library.get::<PluginInitFn>(b"mta_plugin_init\0")
            .map_err(|error| Error::InvalidParameter(format!(
                "failed to load plugin registration symbol from '{}': {}",
                path, error
            )))?;
        init_plugin(MTA_ABI_VERSION, mta_register_plugin as *mut std::ffi::c_void)
    };

    if status != mta_status_t::MTA_SUCCESS {
        return Err(Error::CallbackError(status));
    }

    LIBRARIES.lock().expect("loaded plugin registry mutex was poisoned").push(library);

    return Ok(());
}

/// Load a model from `load_from`, using the given options.
pub fn load_model(
    plugin_name: Option<&str>,
    load_from: &CStr,
    options_json: &CStr,
) -> Result<Model, Error> {
    let plugins = PLUGINS.lock().expect("plugin registry mutex was poisoned");

    if let Some(plugin_name) = plugin_name {
        for plugin in plugins.iter() {
            if plugin.name() == plugin_name {
                return plugin.load_model(load_from, options_json);
            }
        }

        return Err(Error::InvalidParameter(format!(
            "no plugin named '{}' is registered",
            plugin_name
        )));
    }

    for plugin in plugins.iter() {
        match plugin.load_model(load_from, options_json) {
            Ok(model) => return Ok(model),
            Err(e) => {
                if let Error::CallbackError(mta_status_t::MTA_MODEL_NOT_SUPPORTED_ERROR) = e {
                    // try the next plugin
                    continue;
                } else {
                    return Err(e);
                }
            }
        }
    }

    let message = if plugins.is_empty() {
        "no plugin is registered".into()
    } else {
        format!(
            "tried the following plugins, but none could load the model: {}",
            plugins.iter().map(|p| p.name()).collect::<Vec<_>>().join(", ")
        )
    };

    return Err(Error::InvalidParameter(format!(
        "failed to load model from '{}': {}",
        load_from.to_string_lossy(),
        message
    )));
}
