name: Julia tests

on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

concurrency:
  group: julia-tests-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  rust-tests:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / Julia ${{ matrix.julia-version }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            julia-version: "1.6"

          - os: ubuntu-20.04
            julia-version: "1.9"

          - os: macos-11
            julia-version: "1.9"

          # TODO
          # - os: windows-2019
          #   julia-version: "1.9"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.3
        with:
          version: "v0.5.4"

      - name: Setup sccache environnement variables
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "CMAKE_C_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
          echo "CMAKE_CXX_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV

      - name: setup package
        run: |
          julia -e 'using Pkg; Pkg.add(url="https://github.com/Luthaf/Metatensor_jll.jl")'
          julia -e 'using Pkg; Pkg.develop(path="./julia")'

      - name: build local version of libmetatensor
        run: julia julia/deps/build_local.jl

      - name: run tests
        run: julia --check-bounds=yes --inline=no -e 'using Pkg; Pkg.test("Metatensor"; coverage=true)'
