name: Python tests

on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

concurrency:
  group: python-tests-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  python-tests:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            python-version: "3.7"
          - os: ubuntu-20.04
            python-version: "3.10"
          - os: macos-11
            python-version: "3.10"
    steps:
      - uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Setup sccache environnement variables
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "CMAKE_C_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
          echo "CMAKE_CXX_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV

      - name: install tests dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: run Python tests
        run: tox
        env:
          PIP_VERBOSE: "1"

      - name: check we can build the wheels
        run: tox -e build-tests
