name: Regression tests

on:
  push:
    branches: [main]
  pull_request:
    # Check all PR

concurrency:
  group: regtests-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  regtests:
    runs-on: ubuntu-24.04
    name: regression tests
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: setup sccache
        uses: mozilla-actions/sccache-action@v0.0.11
        with:
          version: "v0.10.0"

      - name: cache the models
        uses: actions/cache@v6
        with:
          path: regtests/cache
          key: metatomic-regtests-${{ hashFiles('regtests/models.lock') }}
          restore-keys: metatomic-regtests-

      - name: install python dependencies
        run: python -m pip install tox

      - name: run regression tests
        run: tox -e regtests
        env:
          PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: sccache
          CMAKE_C_COMPILER_LAUNCHER: sccache
          CMAKE_CXX_COMPILER_LAUNCHER: sccache
