name: Test

on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / rust ${{ matrix.rust-version }} / ${{ matrix.build-type }} ${{ matrix.extra-name }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            rust-version: stable
            rust-target: x86_64-unknown-linux-gnu
            build-type: debug
            # test without ndarray feature
          - os: ubuntu-18.04
            rust-version: stable
            rust-target: x86_64-unknown-linux-gnu
            build-type: release
            cargo-build-flags: --release --features=ndarray
          - os: ubuntu-18.04
            rust-version: 1.53
            rust-target: x86_64-unknown-linux-gnu
            build-type: debug
            cargo-build-flags: --features=ndarray
          # check the build on a stock Ubuntu 18.04, including cmake 3.10
          - os: ubuntu-18.04
            rust-version: from Ubuntu
            container: ubuntu:18.04
            rust-target: x86_64-unknown-linux-gnu
            build-type: debug
            cargo-build-flags: --features=ndarray
          - os: macos-10.15
            rust-version: stable
            rust-target: x86_64-apple-darwin
            build-type: debug
            cargo-build-flags: --features=ndarray
    steps:
      - name: install dependencies in container
        if: matrix.container == 'ubuntu:18.04'
        run: |
          apt-get update
          apt-get install -y software-properties-common
          add-apt-repository -y ppa:git-core/ppa
          apt-get update
          apt-get install -y cmake make gcc g++ git curl rustc

          # workaround https://github.com/actions/checkout/issues/760
          git config --global --add safe.directory /__w/equistore/equistore

      - uses: actions/checkout@v2

      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: setup rust
        uses: actions-rs/toolchain@v1
        if: "!matrix.container"
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}
          default: true
          target: ${{ matrix.rust-target }}

      - name: install tests dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox black flake8

      - name: rust tests
        run: cargo test --target ${{ matrix.rust-target }} ${{ matrix.cargo-build-flags }}

      - name: python tests
        run: tox
